config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
    resources :post_images, only: [:index, :show, :destroy]
    end

  devise_for :admins
  root 'admin/users#index'

  devise_for :users
  root 'post_images#index'
  resources :post_images do
  	resource :favorites, only: [:create, :destroy]
  	resource :post_comments, only: [:create, :destroy, :edit, :update]
  end
  get 'favorites', to: 'favorites#index'
  delete 'post_images/:post_image_id/post_comments/destroy/:id', to: 'post_comments#destroy',as:'destroy_post_comment'
  resources :users, only: [:show, :edit, :destroy, :update, :top]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :post_image
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
    belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord
	belongs_to :user
	attachment :image
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	validates :image, presence: true
	validates :caption, presence: true
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :icon
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ActionController::Base
  	protected
  	def configure_permitted_parameters
  		devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
        devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
 	end
 	before_action :authenticate_admin!

 	def after_sign_in_path_for(resource)
	  if admin_signed_in?
	  	 admin_users_path
     elsif user_signed_in?
     	 post_images_path
     	else
         root_path
     end
    end

 	 def after_sign_out_path_for(resource)
         post_images_path
    end

    def after_sign_up_path_for(resource)
    if user_signed_up?
     	 post_images_path
      else
         root_path
    end
    end
end

app/controllers/admin/post_images_controller.rb
class Admin::PostImagesController < Admin::ApplicationController
	 before_action :authenticate_admin!
	def index
		@post_images = PostImage.page(params[:page]).reverse_order
	end

	def destroy
	    @post_image = PostImage.find(params[:id])
	    @post_image.destroy
	    # redirect_to admin_user_path(user.id)
        redirect_to admin_users_path
	end

	def show
	end

	private
    def post_image_params
        params.require(:post_image).permit(:image, :caption, :user_id)
    end


end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
   before_action :authenticate_admin!
  def show
  	@user = User.find(params[:id])
  	@post_images = @user.post_images.page(params[:page]).reverse_order
  end

  def index
    @user = User.find_by(params[:id])
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :icon, :email, :self_introduction)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  	protected
  	def configure_permitted_parameters
  		devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
        devise_parameter_sanitizer.permit(:sign_im, keys: [:email])
 	end
 	# before_action :authenticate_user!
 	def after_sign_in_path_for(resource)
	  if admin_signed_in?
	  	 admin_users_path
     elsif user_signed_in?
     	 post_images_path
     	else
       post_images_path
     end
    end

 	 def after_sign_out_path_for(resource)
         post_images_path
    end

    def after_sign_up_path_for(resource)
    if user_signed_up?
     	 post_images_path
      else
       post_images_path
    end
    end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		post_image = PostImage.find(params[:post_image_id])
        favorite = current_user.favorites.new(post_image_id: post_image.id)
        favorite.save
        redirect_to post_image_path(post_image)
	end

	def destroy
		post_image = PostImage.find(params[:post_image_id])
        favorite = current_user.favorites.find_by(post_image_id: post_image.id)
        favorite.destroy
        redirect_to post_image_path(post_image)
	end

	def index
		favorites = current_user.favorites
	end

end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
	def create
		post_image = PostImage.find(params[:post_image_id])
		comment = current_user.post_comments.new(post_comment_params)
	    comment.post_image_id = post_image.id
	    comment.save
	    redirect_to post_image_path(post_image)
	end

	def destroy
		comment = PostComment.find(params[:id])
		#post_image_id = comment.post_image_id
		comment.destroy
	    redirect_to post_image_path(params[:post_image_id])
	end

	private
	def post_comment_params
		params.require(:post_comment).permit(:user_id, :post_image_id, :comment)
	end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
	# 非ログイン時index以外非表示
	before_action :authenticate_user!, except: [:index]

	def new
		@post_image = PostImage.new
	end

	def create
		@post_image = PostImage.new(post_image_params)
	    @post_image.user_id = current_user.id
	    if @post_image.save
			redirect_to post_images_path
		else
			render :new
		end
	end

	def index
		@post_images = PostImage.page(params[:page]).reverse_order
	end

	def show
		@post_image = PostImage.find_by_id(params[:id])
		@post_comment = PostComment.new
	end

	def destroy
	    @post_image = PostImage.find(params[:id])
	    @post_image.destroy
	    redirect_to post_images_path
	end

	private
    def post_image_params
        params.require(:post_image).permit(:image, :caption, :user_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  	@user = User.find(params[:id])
  	@post_images = @user.post_images.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
    redirect_to post_images_path
    else
    render 'edit'
    end
   end

  private
  def user_params
    params.require(:user).permit(:name, :icon, :email, :self_introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<div class="container">
    <div class="row">
        <div class="position">
            <div class="col-md-1"></div>
            <div class="col-md-5">
                <div class="admin-text">
                    <%= image_tag 'img/usericon1.png', :size=>"300×300" %> User管理
                </div>
            </div>
            <div class="col-md-5">
                <%= link_to "管理者ログアウト", destroy_admin_session_path, method: :delete,class:"admin-link" %>
            </div>
            <div class="col-md-1"></div>
        </div>
        <div class="row">
            <div class="col-md-10 col-sm-offset-1">
                <table class="table">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>アイコン</th>
                            <th>会員名</th>
                            <th>メールアドレス</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @users.each do |user| %>
                        <tr>
                            <td>
                                <%= user.id %>
                            </td>
                            <td>
                                <%= link_to admin_user_path(user.id) do %>
                                <%= attachment_image_tag user, :icon, :size =>'100x100', class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %>
                                <% end %>
                            </td>
                            <td>
                                <%= user.name %>
                            </td>
                            <td>
                                <%= user.email %>
                            </td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

app/views/admin/users/show.html.erb
<div class="container">
    <div class="row">
        <div class="admin-user">
            <br>
            <!-- ユーザー画像追加 -->
            <div class="col-md-4">
                <%= attachment_image_tag @user, :icon, :fill, 80, 80, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
                <h5 class="profile-name">
                    ユーザー名：
                    <%= @user.name %><br>
                    自己紹介：
                    <%= @user.self_introduction %><br>
                    メールアドレス：
                    <%= @user.email %>
                </h5>
                <%= button_to  "退会させる", admin_user_path, class:"admin_submit", method: :delete, "data-confirm" => "本当に退会させますか？" %>
            </div>
            <!-- カレントユーザーが投稿した画像一覧 -->
            <div class="col-md-8">
                <% @post_images.each do |post_image| %>
                <div class="col-md-4">
                    <div class="block-image">
                        <%= link_to post_image_path(post_image.id) do %>
                        <%= attachment_image_tag post_image, :image, :size =>'200x200' %>
                        <% end %>
                    </div>
                    <%= button_to  '削除',  admin_post_image_path(post_image.id), method: :delete,class:"admin_submit" %>
                    <!-- kaminari表示件数 -->
                </div>
                <% end %>
                <%= paginate @post_images, class: "paginate" %>
            </div>
        </div>
    </div>
    <%= link_to "戻る", admin_users_path, class:"admin-link" %>
</div>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/favorites/index.html.erb
<div class="container">
    <div class="row">
        <div class="position">
            <div class="fadein1">
                <div class="title-text">favorites</div>
            </div>
        </div>
        <div class="row">
            <div class="fadein1">
                <div class="sliderArea">
                    <div class="sliderWide">
                        <div class="slider">
                            <% @current_user.favorites.each do |favorite| %>
                            <!-- <div class="col-md-3"> -->
                            <%= link_to post_image_path(favorite.post_image.id) do %>
                            <%= attachment_image_tag favorite.post_image, :image, :size =>'200x200' %>
                            <% end %>
                            <!-- </div> -->
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <title>Diver</title>
</head>

<body>

    <%= yield %>

</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <title>Diver</title>
</head>

<body>
    <!-- ヘッダー -->
    <div class="header">
            <%= link_to post_images_path do %>
            <%= image_tag 'img/02diver_s.png', :class=>"header-logo" %>
            <%= image_tag 'img/divingram.png' %>
            <% end %>

        <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
            <li>
                <%= link_to 'マイページ', user_path(current_user.id),class:"header-link" %>
            </li>
            <li>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class:"header-link" %>
            </li>
        </ul>
        <% else %>
        <ul class="nav navbar-nav navbar-right">
            <li>
                <%= link_to "新規登録", new_user_registration_path,class:"header-link" %>
            </li>
            <li>
                <%= link_to "ログイン", new_user_session_path,class:"header-link" %>
            </li>
            <% end %>
        </ul>
    </div>
    <!-- 泡CSS -->
    <div class="bubbles">
        <div class="bubble"></div>
        <div class="bubble"></div>
        <div class="bubble"></div>
        <div class="bubble"></div>
        <div class="bubble"></div>
        <div class="bubble"></div>
        <div class="bubble"></div>
        <div class="bubble"></div>
        <div class="bubble"></div>
        <div class="bubble"></div>
        <div class="bubble"></div>
        <div class="bubble"></div>
        <div class="bubble"></div>
        <div class="bubble"></div>
        <div class="bubble"></div>
        <div class="bubble"></div>
        <div class="bubble"></div>

            <div class="wrapper">
                <%= yield %>
            </div>
    </div>
    <footer>
        <div class="footer-text">Divingram 2019</div>
    </footer>

    <!-- slickの設定内容 -->
    <script type="text/javascript">
    //top一覧スライド
    $(document).ready(function() {
        $('.slide1').slick({
            autoplay: true, //自動再生
            dots: true, //ドットのナビゲーションを表示
            infinite: true, //スライドのループ有効化
            speed: 800, //切り替えのスピード（小さくすると速くなる）
            fade: true, //フェードの有効化
            cssEase: 'cubic-bezier(.645, .045, .355, 1)'
        });
    });
    // / いいね一覧スライド
    $(document).ready(function() {
        $('.slider').slick({
            autoplay: true,
            centerMode: true,
            centerPadding: '5%',
            dots: true,
            focusOnSelect: true,
            infinite: true,
            touchMove: true
        });
    });

// postimageふわっと出てくる
    $(function(){
    $(window).scroll(function (){
        $('.fadein').each(function(){
            var elemPos = $(this).offset().top;
            var scroll = $(window).scrollTop();
            var windowHeight = $(window).height();
            if (scroll > elemPos - windowHeight + 200){
                $(this).addClass('scrollin');
            }
        });
    });
});



            $(window).on('load',function(){
                $('.ex1').textyleF();
                $('.ex2').textyleF({
                    duration : 3000,
                    delay : 300,
                    easing : 'cubic-bezier(0.785, 0.135, 0.15, 0.86)',
                    callback : function(){
                        $(this).css({
                        color : '#fff',
                        transition : '1s',
                        });
                        $('.desc').css('opacity',1);
                    }
                    });
            });

    </script>


</body>

</html>

app/views/post_images/index.html.erb
<!-- <div class="container"> -->
<!-- スライド -->
<div class="slide1">
    <!-- <div style=background:url('img/850_8073.jpg')> -->
    <div>
        <%= image_tag 'img/850_8073.jpg' %>
        <p class="fade-text">Divingram</p>
    </div>
    <div>
        <%= image_tag 'img/P6050313.jpg' %>
        <p class="fade-text">Divingram</p>
    </div>
</div>
<div class="row">
    <section class="fadein">
        <div class="about-visual">
            <div class="about-visual-left">
                <div class="col-md-6">
                    <p class="ex1">About</p><br><br>
                    <%= image_tag 'img/icon.png', :class=>"header-logo" %><br><br>
                    <p class="ex2">Divingramについて</p>
                </div>
                <div class="col-md-6">
                    <p class="ex2">海の世界を共有しよう</p><br><br>
                    <div class="about-visual-text">
                        <p class="desc">当サイトはダイバー向けの画像投稿サイトです。<br>
                            会員登録することにより、画像の投稿やコメント<br>
                            気に入った画像にリアクションが可能です。<br>
                            一度投稿した画像とコメントは削除のみ可能です。</p>
                    </div>
                </div>
            </div>
        </div>
</div>
</section>
</div>
<div class="row">
    <div class="col-md-8 col-sm-offset-2">
      <br>
        <section class="fadein">
            <div class="title-text">PHOTO GALLERY
            <%= image_tag 'img/01diver_s.png' %></div>
        </section>
        <br><br>
    </div>
</div>
<div class="row">
    <br>
    <div class="col-md-10 col-sm-offset-1">
        <% @post_images.each do |post_image| %>
        <div class="col-md-4">
            <section class="fadein">
                <div class="image">
                  <div class="img_wrap">
                    <%= link_to post_image_path(post_image.id) do %>
                    <%= attachment_image_tag post_image, :image, :size =>'300x300' %>
                    <% end %>
                </div>
              </div>
                <div class="block-content">
                    <%= image_tag 'img/usericon1.png', :class=>"user-icon" %>By
                    <%= post_image.user.name %>
                </div>
            </section>
        </div>
        <% end %>
        <!-- kaminari表示件数 -->
        <%= paginate @post_images, class: "paginate" %>
    </div>
</div>
<!-- </div> -->

app/views/post_images/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8 col-sm-offset-2">
            <div class="position">
                <div class="fadein1">
                    <div class="title-text">upload image</div><br>
                    <%= form_for(@post_image, url: post_images_path) do |f| %>
                    <% if @post_image.errors.any? %>
                    <div id="error_explanation">
                        <h2>
                            <%= @post_image.errors.count %>件のエラーが発生しました。</h2>
                        <ul>
                            <% @post_image.errors.full_messages.each do |message| %>
                            <li>
                                <%= message %>
                            </li>
                            <% end %>
                        </ul>
                    </div>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-sm-offset-3">
                    <%= f.attachment_field :image %>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-6 col-sm-offset-3">
                    <%= f.text_area :caption, class:"form-control", rows:"3", placeholder:"コメントここに" %>
            </div>
            <div class="col-md-6 col-sm-offset-3">
                    <%= f.submit "送信", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
                    <% end %>
            </div>
        </div>
    </div>
</div>

app/views/post_images/show.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<link rel="stylesheet" href="style.css">
<div class="container">
    <div class="row">
        <div class="position">
            <div class="fadein1">
                <div class="col-md-8 col-sm-offset-2">
                    <div class="post-image">
                        <%= attachment_image_tag @post_image, :image, :size =>'600x600' %>
                    </div>
                    <div class="post-content">
                        <!-- 投稿したユーザーの画像表示 -->
                        <%= link_to user_path(@post_image.user) do %>
                        <%= attachment_image_tag @post_image.user, :icon, :fill, 100, 100, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %>
                        <% end %>
                        <div class="post-content-inner mt-100">
                            <br>
                            <%= @post_image.caption %>
                            <br>
                        </div>
                        <%= image_tag 'img/usericon1.png', :class=>"user-icon" %>By
                        <%= @post_image.user.name %>
                        <i class="fa fa-calendar"></i>
                        <%= @post_image.created_at.strftime('%Y/%m/%d') %>
                        <% if @post_image.favorited_by?(current_user) %>
                        <%= link_to post_image_favorites_path(@post_image), method: :delete do %>
                        <i class="fas fa-fish" aria-hidden="true" style="color: blue;"></i>
                        <%= @post_image.favorites.count %> いいね
                        <% end %>
                        <% else %>
                        <%= link_to post_image_favorites_path(@post_image), method: :post do %>
                        <i class="fas fa-fish-o" aria-hidden="true"></i>
                        <%= @post_image.favorites.count %> いいね
                        <% end %>
                        <% end %>
                        <% if @post_image.user == current_user %>
                        <%= link_to "削除", post_image_path(@post_image), method: :delete %>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="comment-list bt style-2" id="comments">
        <div class="float-wrapper">
            <h5 class="comment-count">
                <%= @post_image.post_comments.count %>件コメント</h5>
        </div>
        <div class="row">
            <hr>
            <!-- <ol> -->
            <% @post_image.post_comments.each do |post_comment| %>
            <!-- <li class="comment"> -->
            <div class="col-md-12 col-sm-offset-1">
                <div class="comment-body bb">
                    <div class="comment-avatar">
                        <div class="avatar">
                            <%= attachment_image_tag post_comment.user, :icon, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %><br><br>
                        </div>
                    </div>
                    <div class="comment-text">
                        <%= post_comment.user.name %>
                        <%= post_comment.created_at.strftime('%Y/%m/%d') %>
                    </div>
                    <div class="comment-entry">
                        <%= post_comment.comment %>
                    </div>
                    <% if post_comment.user == current_user %>
                    <%= link_to "削除", destroy_post_comment_path(@post_image,post_comment), method: :delete %>
                    <% end %>
                </div>
                <!-- </li> -->
            </div>
            <% end %>
            <!-- </ol> -->
        </div>
    </div>
    <!-- Add comment section -->
    <div class="row">
        <div class="col-md-8 col-sm-offset-2">
            <%= form_for [@post_image, @post_comment] do |f| %>
            <div class="row">
                <div class="col-md-8 col-sm-offset-2">
                    <%= f.text_area :comment, rows:'3', class: "form-control",placeholder: "コメントをここに" %>
                </div>
            </div>
            <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
            <% end %>
        </div>
    </div>
</div>
</div>
</div>

app/views/users/show.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<link rel="stylesheet" href="style.css">
<div class="container">
    <div class="row">
        <div class="col-md-8 col-sm-offset-2">
            <div class="position">
                <div class="fadein1">
                    <div class="title-text">profile</div>
                </div>
            </div>
        </div>
    </div>
    <!-- ユーザー画像追加 -->
    <div class="row">
        <div class="fadein1">
            <div class="col-md-2"></div>
            <div class="col-md-4">
                <%= attachment_image_tag @user, :icon, :fill, 100,100, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%><br></div>
            <div class="col-md-4">
                <div class="profile-text">
                    ユーザー名：
                    <%= @user.name %><br>
                    自己紹介：
                    <%= @user.self_introduction %><br>
                    <% if @user.id == current_user.id %>
                    メールアドレス：
                    <%= @user.email %>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="fadein1">
                <div class="col-md-8 col-sm-offset-2">
                    <div class="user-link">
                        <%= image_tag 'img/icon2.png' %>
                          <%= link_to "プロフィール編集", edit_user_path(@user),class:"header-link" %>
                        <%= image_tag 'img/icon2.png' %>
                          <%= link_to "いいね一覧", favorites_path, class:"header-link" %>
                        <% end %>
                        <% if @user.id == current_user.id %>
                          <%= image_tag 'img/icon2.png' %>
                        <%= link_to '投稿フォーム', new_post_image_path,class:"header-link" %>
                    </div>
                        <% end %>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8 col-sm-offset-2">
            <br>
            <!-- カレントユーザーが投稿した画像一覧 -->
            <% @post_images.each do |post_image| %>
            <div class="col-md-4">
                <div class="fadein1">
                    <div class="block-image">
                        <%= link_to post_image_path(post_image.id) do %>
                        <%= attachment_image_tag post_image, :image, :size =>'200x200' %>
                        <% end %>
                    </div>
                    <div class="block-content"></div>
                </div>
            </div>
            <% end %>
        </div>
        <!-- kaminari表示件数 -->
        <%= paginate @post_images, class: "paginate" %>
    </div>
</div>